// Single source of truth for every game. The home hub maps over this, and each
// game imports its own entry by slug for consistent titles/colors.
//
// Two browse axes live here alongside the display data: `category` (what the
// game teaches) and `ageBand` (who it is pitched at). Every category/band cell
// holds at least three games, so either axis can be filtered on its own or the
// two combined without ever landing on an empty grid.

export const CATEGORIES = [
  { id: "numbers", label: "Numbers", emoji: "🔢" },
  { id: "words", label: "Words & Letters", emoji: "🔤" },
  { id: "logic", label: "Logic & Memory", emoji: "🧩" },
  { id: "world", label: "World & Me", emoji: "🌍" },
  { id: "creative", label: "Creative", emoji: "🎨" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

// Bands are named by the youngest age they suit; the ranges overlap because a
// game that works at 5 often still works at 7.
export const AGE_BANDS = [
  { id: "little", label: "3–5", emoji: "🐣" },
  { id: "middle", label: "5–7", emoji: "🧒" },
  { id: "big", label: "7–10", emoji: "🎓" },
] as const;

export type AgeBandId = (typeof AGE_BANDS)[number]["id"];

export type GameMeta = {
  slug: string;
  title: string;
  emoji: string;
  subject: string;
  /** Browse grouping on the home hub. */
  category: CategoryId;
  /** Which age band this game is pitched at. */
  ageBand: AgeBandId;
  blurb: string;
  /** Tailwind gradient classes for the card + in-game accent. */
  gradient: string;
  /** Solid accent used for buttons/borders inside the game. */
  accent: string;
  /** How the score is phrased on the home card, e.g. "pts" or "level". */
  scoreLabel: string;
};

export const GAMES: GameMeta[] = [
  {
    slug: "math-pop",
    title: "Math Pop",
    emoji: "🫧",
    subject: "Math",
    category: "numbers",
    ageBand: "big",
    blurb: "Pop the bubble with the right answer before time runs out!",
    gradient: "from-sky-400 to-blue-600",
    accent: "#2563eb",
    scoreLabel: "pts",
  },
  {
    slug: "robot-run",
    title: "Robot Run",
    emoji: "🤖",
    subject: "Coding",
    category: "logic",
    ageBand: "middle",
    blurb: "Snap arrow blocks together to drive the robot to the star.",
    gradient: "from-emerald-400 to-green-600",
    accent: "#059669",
    scoreLabel: "level",
  },
  {
    slug: "critter-match",
    title: "Critter Match",
    emoji: "🐾",
    subject: "Memory",
    category: "logic",
    ageBand: "little",
    blurb: "Flip the cards and match the animal pairs against the clock.",
    gradient: "from-fuchsia-400 to-purple-600",
    accent: "#9333ea",
    scoreLabel: "pts",
  },
  {
    slug: "word-drop",
    title: "Word Drop",
    emoji: "🔤",
    subject: "Spelling",
    category: "words",
    ageBand: "middle",
    blurb: "Catch the falling letters in order to spell the word.",
    gradient: "from-amber-400 to-orange-600",
    accent: "#ea580c",
    scoreLabel: "pts",
  },
  {
    slug: "echo",
    title: "Echo",
    emoji: "🎵",
    subject: "Focus",
    category: "logic",
    ageBand: "little",
    blurb: "Watch, listen, repeat. The glowing pattern grows every round.",
    gradient: "from-rose-400 to-pink-600",
    accent: "#e11d48",
    scoreLabel: "round",
  },
  {
    slug: "coin-count",
    title: "Coin Count",
    emoji: "🪙",
    subject: "Money",
    category: "numbers",
    ageBand: "big",
    blurb: "Tap the coins that add up to the price before the timer runs out.",
    gradient: "from-amber-400 to-yellow-600",
    accent: "#ca8a04",
    scoreLabel: "pts",
  },
  {
    slug: "shape-sort",
    title: "Shape Sort",
    emoji: "🔺",
    subject: "Shapes",
    category: "logic",
    ageBand: "middle",
    blurb: "Sort the falling shapes into the right bins. The rule keeps changing!",
    gradient: "from-cyan-400 to-teal-600",
    accent: "#0d9488",
    scoreLabel: "pts",
  },
  {
    slug: "clock-quest",
    title: "Clock Quest",
    emoji: "🕐",
    subject: "Time",
    category: "numbers",
    ageBand: "big",
    blurb: "Read the clock and tap the matching time. Beat the clock to level up!",
    gradient: "from-indigo-400 to-blue-700",
    accent: "#4338ca",
    scoreLabel: "pts",
  },
  {
    slug: "typing-rocket",
    title: "Typing Rocket",
    emoji: "🚀",
    subject: "Typing",
    category: "logic",
    ageBand: "little",
    blurb: "Tap the right letters to launch the rocket before they reach the ground.",
    gradient: "from-red-500 to-rose-700",
    accent: "#e11d48",
    scoreLabel: "pts",
  },
  {
    slug: "color-mix",
    title: "Color Mix",
    emoji: "🎨",
    subject: "Colors",
    category: "creative",
    ageBand: "middle",
    blurb: "Mix two paints to match the target color. Get it in fewer tries for more stars!",
    gradient: "from-lime-400 to-emerald-600",
    accent: "#16a34a",
    scoreLabel: "pts",
  },
  {
    slug: "arabic-letters",
    title: "Hijaiyah",
    emoji: "📖",
    subject: "Arabic",
    category: "words",
    ageBand: "middle",
    blurb: "Learn the Hijaiyah letters — tap the Arabic letter that matches its name.",
    gradient: "from-emerald-500 to-teal-700",
    accent: "#0f766e",
    scoreLabel: "pts",
  },
  {
    slug: "color-book",
    title: "Color Book",
    emoji: "🖍️",
    subject: "Art",
    category: "creative",
    ageBand: "little",
    blurb: "Pick a colour and fill the picture. Finish it to unlock the next one!",
    gradient: "from-fuchsia-500 to-pink-600",
    accent: "#db2777",
    scoreLabel: "done",
  },
  {
    slug: "tap-tunes",
    title: "Tap Tunes",
    emoji: "🎹",
    subject: "Music",
    category: "creative",
    ageBand: "little",
    blurb: "Tap the falling tiles in time to play the tune. Don't miss a note!",
    gradient: "from-slate-700 to-violet-900",
    accent: "#6d28d9",
    scoreLabel: "pts",
  },
  {
    slug: "count-it",
    title: "Count It",
    emoji: "🔢",
    subject: "Counting",
    category: "numbers",
    ageBand: "little",
    blurb: "Count the things and tap the right number before time runs out.",
    gradient: "from-sky-500 to-blue-700",
    accent: "#1d4ed8",
    scoreLabel: "pts",
  },
  {
    slug: "flag-dash",
    title: "Flag Dash",
    emoji: "🌍",
    subject: "Geography",
    category: "world",
    ageBand: "big",
    blurb: "See the flag, pick the country. How many can you name?",
    gradient: "from-orange-500 to-pink-600",
    accent: "#ea580c",
    scoreLabel: "pts",
  },
  {
    slug: "times-tiles",
    title: "Times Tiles",
    emoji: "🧮",
    subject: "Multiply",
    category: "numbers",
    ageBand: "big",
    blurb: "Pop the tile with the answer to the times-table question. Beat the clock!",
    gradient: "from-teal-500 to-cyan-700",
    accent: "#0e7490",
    scoreLabel: "pts",
  },
  {
    slug: "pattern-party",
    title: "Pattern Party",
    emoji: "🧩",
    subject: "Patterns",
    category: "logic",
    ageBand: "little",
    blurb: "What comes next? Tap the piece that finishes the pattern.",
    gradient: "from-purple-500 to-indigo-700",
    accent: "#6d28d9",
    scoreLabel: "pts",
  },
  {
    slug: "habitat-hop",
    title: "Habitat Hop",
    emoji: "🦁",
    subject: "Science",
    category: "world",
    ageBand: "little",
    blurb: "Sort each animal into Land, Sea or Sky before the timer runs out!",
    gradient: "from-lime-500 to-green-700",
    accent: "#15803d",
    scoreLabel: "pts",
  },
  {
    slug: "rhyme-time",
    title: "Rhyme Time",
    emoji: "🎤",
    subject: "Phonics",
    category: "words",
    ageBand: "middle",
    blurb: "Find the word that rhymes. Keep the streak going for bonus points!",
    gradient: "from-pink-500 to-rose-700",
    accent: "#be123c",
    scoreLabel: "pts",
  },
  {
    slug: "maze-dash",
    title: "Maze Dash",
    emoji: "🧭",
    subject: "Mazes",
    category: "logic",
    ageBand: "middle",
    blurb: "Steer through the maze to reach the star. Don't run into a wall!",
    gradient: "from-amber-500 to-orange-700",
    accent: "#c2410c",
    scoreLabel: "pts",
  },
  {
    slug: "big-number",
    title: "Big Number",
    emoji: "🐘",
    subject: "Compare",
    category: "numbers",
    ageBand: "little",
    blurb: "Two numbers pop up — tap the bigger one before your hearts run out!",
    gradient: "from-blue-400 to-indigo-600",
    accent: "#4f46e5",
    scoreLabel: "pts",
  },
  {
    slug: "odd-one-out",
    title: "Odd One Out",
    emoji: "🔍",
    subject: "Logic",
    category: "logic",
    ageBand: "little",
    blurb: "Three things belong together and one doesn't. Tap the odd one out!",
    gradient: "from-yellow-400 to-amber-600",
    accent: "#d97706",
    scoreLabel: "pts",
  },
  {
    slug: "opposites",
    title: "Opposites",
    emoji: "↔️",
    subject: "Words",
    category: "words",
    ageBand: "middle",
    blurb: "Hot & cold, big & small — tap the word that means the opposite!",
    gradient: "from-teal-400 to-emerald-600",
    accent: "#0d9488",
    scoreLabel: "pts",
  },
  {
    slug: "quick-tap",
    title: "Quick Tap",
    emoji: "⚡",
    subject: "Reflex",
    category: "logic",
    ageBand: "little",
    blurb: "Tap the glowing targets as fast as you can — but dodge the bombs!",
    gradient: "from-violet-500 to-fuchsia-700",
    accent: "#7c3aed",
    scoreLabel: "pts",
  },
  {
    slug: "shadow-match",
    title: "Shadow Match",
    emoji: "🕵️",
    subject: "Visual",
    category: "logic",
    ageBand: "little",
    blurb: "Guess the emoji from its shadow, then tap the one that matches!",
    gradient: "from-slate-500 to-slate-800",
    accent: "#475569",
    scoreLabel: "pts",
  },
  {
    slug: "weather-watch",
    title: "Weather Watch",
    emoji: "🌦️",
    subject: "Weather",
    category: "world",
    ageBand: "little",
    blurb: "See the scene, tap the matching weather — sunny, rainy, snowy and more!",
    gradient: "from-sky-300 to-indigo-500",
    accent: "#3730a3",
    scoreLabel: "pts",
  },
  {
    slug: "body-bop",
    title: "Body Bop",
    emoji: "🧍",
    subject: "Anatomy",
    category: "world",
    ageBand: "middle",
    blurb: "Read the body part name, then tap the matching tile before your hearts run out!",
    gradient: "from-orange-300 to-rose-500",
    accent: "#dc2626",
    scoreLabel: "pts",
  },
  {
    slug: "abc-order",
    title: "ABC Order",
    emoji: "🔡",
    subject: "Alphabet",
    category: "words",
    ageBand: "little",
    blurb: "Tap the shuffled letters in the right alphabetical order!",
    gradient: "from-cyan-500 to-blue-700",
    accent: "#0369a1",
    scoreLabel: "pts",
  },
  {
    slug: "fraction-feast",
    title: "Fraction Feast",
    emoji: "🍕",
    subject: "Fractions",
    category: "numbers",
    ageBand: "big",
    blurb: "See the shaded pizza slices, then tap the matching fraction!",
    gradient: "from-yellow-300 to-red-500",
    accent: "#b91c1c",
    scoreLabel: "pts",
  },
  {
    slug: "feelings",
    title: "Feelings",
    emoji: "🎭",
    subject: "Emotions",
    category: "world",
    ageBand: "big",
    blurb: "See the face, tap the word that names the feeling!",
    gradient: "from-pink-300 to-fuchsia-600",
    accent: "#a21caf",
    scoreLabel: "pts",
  },
  {
    slug: "number-line-hop",
    title: "Number Line Hop",
    emoji: "🐰",
    subject: "Counting",
    category: "numbers",
    ageBand: "little",
    blurb: "A number is missing from the line — tap the tile that fills the gap!",
    gradient: "from-sky-300 to-cyan-600",
    accent: "#0891b2",
    scoreLabel: "pts",
  },
  {
    slug: "first-sound",
    title: "First Sound",
    emoji: "🍎",
    subject: "Phonics",
    category: "words",
    ageBand: "little",
    blurb: "See the picture, tap the letter its name starts with!",
    gradient: "from-orange-300 to-amber-600",
    accent: "#d97706",
    scoreLabel: "pts",
  },
  {
    slug: "letter-hunt",
    title: "Letter Hunt",
    emoji: "🔠",
    subject: "Letters",
    category: "words",
    ageBand: "little",
    blurb: "Find every copy of the target letter before time runs out!",
    gradient: "from-lime-300 to-green-600",
    accent: "#16a34a",
    scoreLabel: "pts",
  },
  {
    slug: "baby-animals",
    title: "Baby Animals",
    emoji: "🐥",
    subject: "Animals",
    category: "world",
    ageBand: "little",
    blurb: "Every animal has a baby — tap the little one that matches!",
    gradient: "from-pink-300 to-rose-500",
    accent: "#e11d48",
    scoreLabel: "pts",
  },
  {
    slug: "sticker-scene",
    title: "Sticker Scene",
    emoji: "🏖️",
    subject: "Play",
    category: "creative",
    ageBand: "little",
    blurb: "Pick a scene and fill it with stickers — no timer, no rules!",
    gradient: "from-fuchsia-300 to-purple-600",
    accent: "#9333ea",
    scoreLabel: "scenes",
  },
  {
    slug: "number-bonds",
    title: "Number Bonds",
    emoji: "🔗",
    subject: "Bonds",
    category: "numbers",
    ageBand: "middle",
    blurb: "Find the partner that completes the number — 7 and what makes 10?",
    gradient: "from-blue-400 to-indigo-600",
    accent: "#4f46e5",
    scoreLabel: "pts",
  },
  {
    slug: "skip-count",
    title: "Skip Count",
    emoji: "🦘",
    subject: "Skip Count",
    category: "numbers",
    ageBand: "middle",
    blurb: "2, 4, 6... tap the number that comes next!",
    gradient: "from-teal-300 to-emerald-600",
    accent: "#059669",
    scoreLabel: "pts",
  },
  {
    slug: "add-ladder",
    title: "Add Ladder",
    emoji: "🪜",
    subject: "Adding",
    category: "numbers",
    ageBand: "middle",
    blurb: "Solve each rung to climb the ladder all the way up!",
    gradient: "from-amber-300 to-orange-600",
    accent: "#ea580c",
    scoreLabel: "pts",
  },
  {
    slug: "plant-parts",
    title: "Plant Parts",
    emoji: "🌱",
    subject: "Plants",
    category: "world",
    ageBand: "middle",
    blurb: "Root, stem, leaf or flower — tap the part that lights up!",
    gradient: "from-green-300 to-emerald-700",
    accent: "#047857",
    scoreLabel: "pts",
  },
  {
    slug: "jobs-tools",
    title: "Jobs & Tools",
    emoji: "🧑‍🚒",
    subject: "Jobs",
    category: "world",
    ageBand: "middle",
    blurb: "Every worker needs a tool — tap the right one for the job!",
    gradient: "from-yellow-300 to-amber-600",
    accent: "#ca8a04",
    scoreLabel: "pts",
  },
  {
    slug: "symmetry-paint",
    title: "Symmetry Paint",
    emoji: "🦋",
    subject: "Symmetry",
    category: "creative",
    ageBand: "middle",
    blurb: "Half the picture is drawn — tap to mirror the other half!",
    gradient: "from-violet-300 to-indigo-600",
    accent: "#6366f1",
    scoreLabel: "level",
  },
  {
    slug: "beat-builder",
    title: "Beat Builder",
    emoji: "🥁",
    subject: "Rhythm",
    category: "creative",
    ageBand: "middle",
    blurb: "Tap out the beat you hear and play it back!",
    gradient: "from-rose-300 to-pink-600",
    accent: "#db2777",
    scoreLabel: "level",
  },
  {
    slug: "spell-it",
    title: "Spell It",
    emoji: "✍️",
    subject: "Spelling",
    category: "words",
    ageBand: "big",
    blurb: "The word flashes then hides — spell it from memory!",
    gradient: "from-cyan-300 to-blue-700",
    accent: "#1d4ed8",
    scoreLabel: "pts",
  },
  {
    slug: "sentence-build",
    title: "Sentence Build",
    emoji: "📝",
    subject: "Grammar",
    category: "words",
    ageBand: "big",
    blurb: "The words are jumbled — tap them in order to fix the sentence!",
    gradient: "from-emerald-300 to-teal-700",
    accent: "#0f766e",
    scoreLabel: "pts",
  },
  {
    slug: "synonyms",
    title: "Synonyms",
    emoji: "💬",
    subject: "Vocabulary",
    category: "words",
    ageBand: "big",
    blurb: "Big, large, huge — tap the word that means the same!",
    gradient: "from-indigo-300 to-violet-700",
    accent: "#7c3aed",
    scoreLabel: "pts",
  },
  {
    slug: "code-loops",
    title: "Code Loops",
    emoji: "🔁",
    subject: "Coding",
    category: "logic",
    ageBand: "big",
    blurb: "Too many blocks? Wrap them in a repeat and let the loop do the work!",
    gradient: "from-slate-400 to-slate-700",
    accent: "#475569",
    scoreLabel: "level",
  },
  {
    slug: "mini-sudoku",
    title: "Mini Sudoku",
    emoji: "🔳",
    subject: "Puzzles",
    category: "logic",
    ageBand: "big",
    blurb: "Every row and column needs one of each — no repeats allowed!",
    gradient: "from-purple-400 to-fuchsia-700",
    accent: "#a21caf",
    scoreLabel: "level",
  },
  {
    slug: "logic-grid",
    title: "Logic Grid",
    emoji: "🧠",
    subject: "Deduction",
    category: "logic",
    ageBand: "big",
    blurb: "Three clues, one answer — tick and cross your way to the solution!",
    gradient: "from-stone-400 to-neutral-700",
    accent: "#57534e",
    scoreLabel: "level",
  },
  {
    slug: "map-quest",
    title: "Map Quest",
    emoji: "🗺️",
    subject: "Maps",
    category: "world",
    ageBand: "big",
    blurb: "Tap the continent or ocean on the map before time runs out!",
    gradient: "from-sky-400 to-indigo-700",
    accent: "#4338ca",
    scoreLabel: "pts",
  },
  {
    slug: "pixel-copy",
    title: "Pixel Copy",
    emoji: "🖼️",
    subject: "Pixel Art",
    category: "creative",
    ageBand: "big",
    blurb: "Copy the picture square by square until it matches perfectly!",
    gradient: "from-red-300 to-rose-700",
    accent: "#be123c",
    scoreLabel: "level",
  },
  {
    slug: "melody-match",
    title: "Melody Match",
    emoji: "🎼",
    subject: "Melody",
    category: "creative",
    ageBand: "big",
    blurb: "Listen to the tune, then play it back — the keys stay dark!",
    gradient: "from-amber-200 to-yellow-600",
    accent: "#b45309",
    scoreLabel: "pts",
  },
  {
    slug: "color-theory",
    title: "Color Theory",
    emoji: "🌈",
    subject: "Color",
    category: "creative",
    ageBand: "big",
    blurb: "Find the colour that sits opposite on the wheel!",
    gradient: "from-pink-400 to-violet-700",
    accent: "#9333ea",
    scoreLabel: "pts",
  },
];

export function getGame(slug: string): GameMeta {
  const g = GAMES.find((x) => x.slug === slug);
  if (!g) throw new Error(`Unknown game: ${slug}`);
  return g;
}

/** Games in one category, home-hub order preserved. */
export function gamesInCategory(category: CategoryId): GameMeta[] {
  return GAMES.filter((g) => g.category === category);
}

/** Games pitched at one age band, home-hub order preserved. */
export function gamesInBand(ageBand: AgeBandId): GameMeta[] {
  return GAMES.filter((g) => g.ageBand === ageBand);
}
